version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        GIT_USERNAME: hyzco
        GIT_PAT: GIT_PAT_TOKEN
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: pw
      DB_NAME: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    command: sh -c 'until nc -z mysql 3306 && nc -z redis 6379; do sleep 1; done; npm run start'  
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        GIT_USERNAME: hyzco
        GIT_PAT: GIT_PAT_TOKEN
    restart: always
    ports:
      - 81:5001
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: db
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql

  redis:
    hostname: redis
    container_name: redis
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: 'redis-server'  

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"   

volumes:
  mysql-data:
  redis-data:


##TODO: Don't hardcode the variables - extract it to env variables